apiVersion: v1
kind: Pod
metadata:
  name: pytest-pod
  labels:
    app: pytest
    component: testing
spec:
  containers:
  - name: pytest-container
    image: python:3.9-slim
    command: ["/bin/bash"]
    args:
      - -c
      - |
        echo "Installing dependencies..."
        pip install pytest pytest-cov pandas scikit-learn
        
        echo "Cloning repository..."
        git clone https://github.com/iamaditya00010/contextq-DE-ML-pipeline.git /workspace
        cd /workspace
        
        echo "Creating data directories..."
        mkdir -p data/bronze data/silver data/gold data/ml_output models
        
        echo "Running pytest with coverage..."
        pytest tests/ -v --cov=scripts --cov-report=term-missing --cov-report=html:htmlcov
        
        echo "Generating test report..."
        echo "Test execution completed at $(date)" > test_report.txt
        
        echo "Keeping pod alive for monitoring..."
        tail -f /dev/null
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    env:
    - name: PYTHONPATH
      value: "/workspace"
  volumes:
  - name: workspace
    emptyDir: {}
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: pytest-service
spec:
  selector:
    app: pytest
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
